### ISSUE TITLE
Intended OS and dig version

### ISSUE THREAD

**Issue by mrl22** [geek4unix/compare-zones#1]
Great script, thank you!

Is there an intended OS or dig version for this? It gives some strange results on MacOS.

Works well on CentOS, but with one zone I do get "Truncated, retrying in TCP mode. " for a TXT record.

**Comment by geek4unix** [comment]
Hi - Interesting results !

It looks like i am using the standard version of dig that comes with OSX Catalina (DiG 9.10.6)
I think there is also a homebrew version too, I had no particular version in mind when i wrote the script.

The truncated notification should not change much ( apart from output not matching ) as this would happen at the server end. Depending on the server config queries with results over a certain size may well switch to tcp.

Do you always get the "Truncated, retrying" for that TXT record ? Is it a 'large' txt record ? 
Does your server support dns over tcp ? ( some have it firewalled by mistake, its not always obvious as some queries succeed ! )

The size of the reply is server dependant and can be upto 4096 if your server supports edns standard, however some are as low as 512 bytes.

Cheers

Neil

--

https://unix.stackexchange.com/questions/545055/unable-to-run-dns-queries-when-response-is-bigger-than-512-bytes-and-truncated

https://ns1.com/blog/when-dns-uses-udp-versus-tcp
